### ISSUE TITLE
[CloudFogServiceBroker]  local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by robert-sanfeliu** [eu-nebulous/cloud-fog-service-broker#12]
On nebulous-cd:

```
Entered in OPT-Multi-triggering with key:  OPT-Triggering-Multi
Optimizer Correlation Id:  29bcdb68f73146eea0bcffc8e6d6faa4
Whole Message Sent from Optimizer Multi: {'when': '2024-09-30T10:09:37.743175417Z', 'body': '[[{"type":"AttributeRequirement","requirementClass":"hardware","requirementAttribute":"ram","requirementOperator":"GEQ","value":"8192"},{"type":"AttributeRequirement","requirementClass":"hardware","requirementAttribute":"cores","requirementOperator":"GEQ","value":"4"},{"type":"NodeTypeRequirement","nodeTypes":["IAAS"],"jobIdForByon":"","jobIdForEDGE":""},{"type":"AttributeRequirement","requirementClass":"cloud","requirementAttribute":"id","requirementOperator":"EQ","value":"c9a625c7-f705-4128-948f-6b5765509029-12"},{"type":"AttributeRequirement","requirementClass":"location","requirementAttribute":"name","requirementOperator":"IN","value":"us-east-1"}]]', 'metaData': {'user': 'admin'}}
-------------------------------------------------
Extracted body from Optimizer Message: [[{'type': 'AttributeRequirement', 'requirementClass': 'hardware', 'requirementAttribute': 'ram', 'requirementOperator': 'GEQ', 'value': '8192'}, {'type': 'AttributeRequirement', 'requirementClass': 'hardware', 'requirementAttribute': 'cores', 'requirementOperator': 'GEQ', 'value': '4'}, {'type': 'NodeTypeRequirement', 'nodeTypes': ['IAAS'], 'jobIdForByon': '', 'jobIdForEDGE': ''}, {'type': 'AttributeRequirement', 'requirementClass': 'cloud', 'requirementAttribute': 'id', 'requirementOperator': 'EQ', 'value': 'c9a625c7-f705-4128-948f-6b5765509029-12'}, {'type': 'AttributeRequirement', 'requirementClass': 'location', 'requirementAttribute': 'name', 'requirementOperator': 'IN', 'value': 'us-east-1'}]]
-------------------------------------------------
Process List:  1
Request to SAL: {'metaData': {'user': 'admin'}, 'body': '[{"type": "AttributeRequirement", "requirementClass": "hardware", "requirementAttribute": "ram", "requirementOperator": "GEQ", "value": "8192"}, {"type": "AttributeRequirement", "requirementClass": "hardware", "requirementAttribute": "cores", "requirementOperator": "GEQ", "value": "4"}, {"type": "NodeTypeRequirement", "nodeTypes": ["IAAS"], "jobIdForByon": "", "jobIdForEDGE": ""}, {"type": "AttributeRequirement", "requirementClass": "cloud", "requirementAttribute": "id", "requirementOperator": "EQ", "value": "c9a625c7-f705-4128-948f-6b5765509029-12"}, {"type": "AttributeRequirement", "requirementClass": "location", "requirementAttribute": "name", "requirementOperator": "IN", "value": "us-east-1"}]'}
Request to SAL is OK:  1
Number of Nodes: 66 in List: 1
------------------------------------------------------------
----------------List Loop is Ended--------------------------
Total Lists and Requests to SAL:  1
Total unique nodes: 66
Total Nodes in SAL's reply: 66
node_ids: ['8a748485924248c501924260cabe000c', '8a748485924248c501924260caef0010', '8a748485924248c501924260d0170032', '8a748485924248c501924260d0680034', '8a748485924248c501924260d1f5003c', '8a748485924248c501924260dc1a0070', '8a748485924248c501924260dd1b0074', '8a748485924248c501924260e474009e', '8a748485924248c501924260e53b00a2', '8a748485924248c501924260e64c00a8', '8a748485924248c501924260ec4400c2', '8a748485924248c501924260f2b600e4', '8a748485924248c50192426108600152', '8a748485924248c5019242610ca20168', '8a748485924248c5019242611b7501b0', '8a748485924248c5019242611c6f01b4', '8a748485924248c501924261295501f2', '8a748485924248c5019242612c9f0204', '8a748485924248c5019242612f920214', '8a748485924248c50192426135990228', '8a748485924248c501924261378c022c', '8a748485924248c50192426138590230', '8a748485924248c5019242613e5f023a', '8a748485924248c50192426143a40258', '8a748485924248c5019242614440025c', '8a748485924248c501924261595002bc', '8a748485924248c501924261618302de', '8a748485924248c501924261630c02e0', '8a748485924248c501924261698b02ec', '8a748485924248c501924261772b0308', '8a748485924248c50192426177cf030c', '8a748485924248c5019242618871035e', '8a748485924248c5019242618c360372', '8a748485924248c5019242618ecb0380', '8a748485924248c50192426192cd0390', '8a748485924248c501924261987603ae', '8a748485924248c501924261a0a003d2', '8a748485924248c501924261aa740408', '8a748485924248c501924261b13d0426', '8a748485924248c501924261b23f042c', '8a748485924248c501924261bcd2044c', '8a748485924248c501924261bec20456', '8a748485924248c501924261bfed045c', '8a748485924248c501924261c1820464', '8a748485924248c501924261c43e046c', '8a748485924248c501924261c7cd047e', '8a748485924248c501924261c9b40488', '8a748485924248c501924261cb160490', '8a748485924248c501924261cfc804a8', '8a748485924248c501924261d53b04c6', '8a748485924248c501924261e4d90514', '8a748485924248c501924261e5a60518', '8a748485924248c501924261e8000524', '8a748485924248c501924261e932052a', '8a748485924248c501924261e9bf052c', '8a748485924248c501924261fcde0590', '8a748485924248c5019242620e1d05e4', '8a748485924248c5019242621b310626', '8a748485924248c5019242621c62062c', '8a748485924248c5019242621dc30634', '8a748485924248c5019242621eef063a', '8a748485924248c5019242622209064a', '8a748485924248c5019242622ced066e', '8a748485924248c5019242622d630670', '8a748485924248c501924262301f067e', '8a748485924248c501924262320f0688']
There are 66 nodes for Evaluation
Exception in thread Thread-18 (on_message):
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/flask_app/activemq.py", line 387, in on_message
    evaluation_results = perform_evaluation(data_table, relative_wr_data, immediate_wr_data,
  File "/flask_app/Evaluation.py", line 147, in perform_evaluation
    if not res.success:
UnboundLocalError: local variable 'res' referenced before assignment

```

**Comment by rudi** [comment]
Looks like the `if not res.success:` block should be inside the `for dmu_index in range(num_of_dmus):` loop instead of after the loop has terminated, maybe?

**Comment by gregkoron** [comment]
I cannot replicate the error. Please find attached the results of the evaluation of the 66 nodes returned by SAL to CFSB.

[CFSBResponse.json](https://github.com/user-attachments/files/17191715/CFSBResponse.json)

However, given this report and Rudi's comment I have made a better workaround to handle issues that may appear in CFSB. It can be found in branch "_Handling_Issues_".
